name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 18.x
      - name: Yarn
        run: npm install -g yarn

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          
      - name: Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn publish --access public
