name: Upload Release Assets

on:
  release:
    types:
      - created

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 18.x

      - name: Install Yarn
        run: npm install -g yarn
       
      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Create dist archive
        run: |
          tar -czf dist.tar.gz -C dist .
          
      - name: Upload dist as release asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist.tar.gz
          asset_name: dist.tar.gz
          asset_content_type: application/gzip 